/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CsvImgPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/csv.ts
function parseCsv(input) {
  const text = stripBom(input);
  const matrix = parseToMatrix(text);
  if (matrix.length === 0) {
    return { headers: [], rows: [], matrix: [] };
  }
  const headers = matrix[0].map((h) => h.trim());
  const rows = [];
  for (let r = 1; r < matrix.length; r++) {
    const cells = matrix[r];
    if (cells.length === 1 && cells[0].trim() === "")
      continue;
    const obj = {};
    for (let c = 0; c < headers.length; c++) {
      obj[headers[c]] = c < cells.length ? cells[c] : "";
    }
    rows.push(obj);
  }
  return { headers, rows, matrix };
}
function stripBom(s) {
  return s.charCodeAt(0) === 65279 ? s.slice(1) : s;
}
function parseToMatrix(text) {
  const out = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  let i = 0;
  const n = text.length;
  const pushField = () => {
    row.push(field);
    field = "";
  };
  const pushRow = () => {
    pushField();
    out.push(row);
    row = [];
  };
  while (i < n) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i += 2;
          continue;
        }
        inQuotes = false;
        i++;
        continue;
      }
      field += ch;
      i++;
      continue;
    }
    if (ch === '"') {
      inQuotes = true;
      i++;
      continue;
    }
    if (ch === ",") {
      pushField();
      i++;
      continue;
    }
    if (ch === "\r") {
      if (text[i + 1] === "\n") {
        pushRow();
        i += 2;
        continue;
      }
      pushRow();
      i++;
      continue;
    }
    if (ch === "\n") {
      pushRow();
      i++;
      continue;
    }
    field += ch;
    i++;
  }
  if (field.length > 0 || row.length > 0) {
    pushRow();
  }
  return out;
}

// src/image.ts
var import_obsidian = require("obsidian");
var IMAGE_EXTENSIONS = [
  "png",
  "jpg",
  "jpeg",
  "gif",
  "webp",
  "svg",
  "bmp",
  "avif"
];
var IMG_EXT_RE = new RegExp(`\\.(${IMAGE_EXTENSIONS.join("|")})$`, "i");
function splitImages(cell) {
  return cell.split(";").map((s) => s.trim()).filter((s) => s.length > 0);
}
function looksLikeImagePath(value) {
  return IMG_EXT_RE.test(value.trim());
}
function cellHasImage(cell) {
  return splitImages(cell).some(looksLikeImagePath);
}
function detectImageColumns(headers, rows, forced) {
  var _a;
  if (forced && forced.length > 0) {
    return new Set(forced);
  }
  const result = /* @__PURE__ */ new Set();
  for (const h of headers) {
    let nonEmpty = 0;
    let imageLike = 0;
    for (const row of rows) {
      const v = ((_a = row[h]) != null ? _a : "").trim();
      if (v === "")
        continue;
      nonEmpty++;
      if (cellHasImage(v))
        imageLike++;
    }
    if (nonEmpty > 0 && imageLike / nonEmpty >= 0.5) {
      result.add(h);
    }
  }
  return result;
}
function dirOf(filePath) {
  return filePath.includes("/") ? filePath.slice(0, filePath.lastIndexOf("/")) : "";
}
function resolveImageSrc(app, rawPath, baseDirs, linkSourcePath) {
  const path = rawPath.trim();
  if (path === "")
    return null;
  if (/^(https?:|data:|file:)/i.test(path)) {
    return path;
  }
  const candidates = [];
  for (const dir of baseDirs) {
    candidates.push(dir ? (0, import_obsidian.normalizePath)(`${dir}/${path}`) : (0, import_obsidian.normalizePath)(path));
  }
  candidates.push((0, import_obsidian.normalizePath)(path));
  const seen = /* @__PURE__ */ new Set();
  for (const c of candidates) {
    if (seen.has(c))
      continue;
    seen.add(c);
    const file = app.vault.getAbstractFileByPath(c);
    if (file instanceof import_obsidian.TFile) {
      return app.vault.getResourcePath(file);
    }
  }
  const linked = app.metadataCache.getFirstLinkpathDest(path, linkSourcePath);
  if (linked instanceof import_obsidian.TFile) {
    return app.vault.getResourcePath(linked);
  }
  return null;
}

// src/render.ts
function appendImage(parent, ctx, rawPath) {
  const src = resolveImageSrc(
    ctx.app,
    rawPath,
    ctx.baseDirs,
    ctx.linkSourcePath
  );
  if (src) {
    const img = parent.createEl("img", { cls: "csv-img-thumb" });
    img.src = src;
    img.alt = rawPath;
    img.style.maxWidth = `${ctx.thumbSize}px`;
    img.style.maxHeight = `${ctx.thumbSize}px`;
    img.title = rawPath;
  } else {
    const chip = parent.createSpan({ cls: "csv-img-missing" });
    chip.setText(`\u26A0 ${rawPath}`);
    chip.title = "\uC774\uBBF8\uC9C0\uB97C \uCC3E\uC744 \uC218 \uC5C6\uC74C (\uACBD\uB85C \uD655\uC778)";
  }
}
function appendCellImages(parent, ctx, cell) {
  const wrap = parent.createDiv({ cls: "csv-img-cellimgs" });
  for (const p of splitImages(cell)) {
    appendImage(wrap, ctx, p);
  }
}
function renderGenericTable(el, csv, ctx, forcedImages) {
  var _a;
  const imageCols = detectImageColumns(csv.headers, csv.rows, forcedImages);
  const container = el.createDiv({ cls: "csv-img-container" });
  const table = container.createEl("table", { cls: "csv-img-table" });
  const thead = table.createEl("thead");
  const headRow = thead.createEl("tr");
  for (const h of csv.headers) {
    const th = headRow.createEl("th");
    th.setText(h);
    if (imageCols.has(h))
      th.addClass("csv-img-col");
  }
  const tbody = table.createEl("tbody");
  for (const row of csv.rows) {
    const tr = tbody.createEl("tr");
    for (const h of csv.headers) {
      const td = tr.createEl("td");
      const val = (_a = row[h]) != null ? _a : "";
      if (imageCols.has(h) && cellHasImage(val)) {
        appendCellImages(td, ctx, val);
      } else {
        td.setText(val);
      }
    }
  }
}
function renderAssetsGallery(el, csv, ctx) {
  var _a, _b, _c, _d, _e, _f;
  const s = ctx.settings;
  const fileCol = pickCol(csv.headers, s.assetsFileColumn, "file");
  const capCol = pickCol(csv.headers, s.assetsCaptionColumn, "caption");
  const srcCol = pickCol(csv.headers, s.assetsSourceColumn, "source");
  const licCol = pickCol(csv.headers, s.assetsLicenseColumn, "license");
  const linkTblCol = pickCol(csv.headers, s.assetsLinkTableColumn, "linked_table");
  const linkIdCol = pickCol(csv.headers, s.assetsLinkIdColumn, "linked_id");
  const grid = el.createDiv({ cls: "csv-img-gallery" });
  for (const row of csv.rows) {
    const filesRaw = fileCol ? (_a = row[fileCol]) != null ? _a : "" : "";
    if (filesRaw.trim() === "")
      continue;
    const card = grid.createDiv({ cls: "csv-img-card" });
    const imgsWrap = card.createDiv({ cls: "csv-img-card-imgs" });
    for (const p of splitImages(filesRaw)) {
      appendImage(imgsWrap, ctx, p);
    }
    const caption = capCol ? (_b = row[capCol]) != null ? _b : "" : "";
    if (caption.trim()) {
      card.createDiv({ cls: "csv-img-card-caption", text: caption });
    }
    const metaBits = [];
    const source = srcCol ? (_c = row[srcCol]) != null ? _c : "" : "";
    const license = licCol ? (_d = row[licCol]) != null ? _d : "" : "";
    if (source.trim())
      metaBits.push(source.trim());
    if (license.trim())
      metaBits.push(license.trim());
    if (metaBits.length) {
      card.createDiv({
        cls: "csv-img-card-meta",
        text: metaBits.join(" \xB7 ")
      });
    }
    const linkTbl = linkTblCol ? ((_e = row[linkTblCol]) != null ? _e : "").trim() : "";
    const linkId = linkIdCol ? ((_f = row[linkIdCol]) != null ? _f : "").trim() : "";
    const badge = card.createDiv({ cls: "csv-img-card-badge" });
    if (linkTbl || linkId) {
      badge.addClass("is-linked");
      badge.setText(`\uC0BD\uD654 \u2192 ${linkTbl}${linkId ? "/" + linkId : ""}`);
    } else {
      badge.addClass("is-gallery");
      badge.setText("\uAC24\uB7EC\uB9AC");
    }
  }
}
function pickCol(headers, configured, fallback) {
  if (configured && headers.includes(configured))
    return configured;
  if (headers.includes(fallback))
    return fallback;
  return null;
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  thumbSize: 160,
  forcedImageColumns: [],
  // Defaults match ai-love-island docs/adr/0002 assets.csv schema.
  assetsFileColumn: "file",
  assetsCaptionColumn: "caption",
  assetsSourceColumn: "source",
  assetsLicenseColumn: "license",
  assetsLinkTableColumn: "linked_table",
  assetsLinkIdColumn: "linked_id"
};
var KNOWN_KEYS = /* @__PURE__ */ new Set(["path", "preset", "images", "size", "src", "file"]);
function parseBlockOptions(source) {
  const opts = {};
  const inlineLines = [];
  const lines = source.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    const m = trimmed.match(/^([A-Za-z_]+)\s*:\s*(.*)$/);
    if (m && KNOWN_KEYS.has(m[1].toLowerCase())) {
      const key = m[1].toLowerCase();
      const val = m[2].trim();
      if (key === "path" || key === "src" || key === "file") {
        opts.path = stripQuotes(val);
      } else if (key === "preset") {
        opts.preset = val.toLowerCase();
      } else if (key === "images") {
        opts.images = val.split(",").map((s) => s.trim()).filter(Boolean);
      } else if (key === "size") {
        const num = parseInt(val, 10);
        if (!isNaN(num))
          opts.size = num;
      }
      continue;
    }
    inlineLines.push(line);
  }
  const inline = inlineLines.join("\n").trim();
  if (inline.length > 0)
    opts.inlineCsv = inline;
  return opts;
}
function stripQuotes(s) {
  if (s.startsWith('"') && s.endsWith('"') || s.startsWith("'") && s.endsWith("'")) {
    return s.slice(1, -1);
  }
  return s;
}

// src/main.ts
var CsvImgPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerMarkdownCodeBlockProcessor(
      "csv-img",
      (source, el, ctx) => this.processBlock(source, el, ctx)
    );
    this.addSettingTab(new CsvImgSettingTab(this.app, this));
  }
  async processBlock(source, el, ctx) {
    var _a, _b, _c;
    const opts = parseBlockOptions(source);
    let csvText = null;
    try {
      csvText = await this.loadCsvText(opts, ctx.sourcePath);
    } catch (e) {
      this.renderError(el, String((_a = e == null ? void 0 : e.message) != null ? _a : e));
      return;
    }
    if (csvText == null) {
      this.renderError(
        el,
        "CSV \uC18C\uC2A4\uAC00 \uC5C6\uC74C. `path: <\uD30C\uC77C.csv>` \uB97C \uC8FC\uAC70\uB098 \uBE14\uB85D \uC548\uC5D0 CSV \uB97C \uC9C1\uC811 \uBD99\uC5EC\uB123\uC73C\uC138\uC694."
      );
      return;
    }
    const csv = parseCsv(csvText);
    if (csv.headers.length === 0) {
      this.renderError(el, "CSV \uAC00 \uBE44\uC5B4 \uC788\uAC70\uB098 \uD5E4\uB354\uAC00 \uC5C6\uC74C.");
      return;
    }
    const noteDir = dirOf(ctx.sourcePath);
    const baseDirs = [noteDir];
    if (opts.path) {
      const csvFile = this.resolveCsvPath(opts.path, ctx.sourcePath);
      if (csvFile) {
        const csvDir = dirOf(csvFile.path);
        if (!baseDirs.includes(csvDir))
          baseDirs.push(csvDir);
      }
    }
    const renderCtx = {
      app: this.app,
      baseDirs,
      linkSourcePath: ctx.sourcePath,
      settings: this.settings,
      thumbSize: (_b = opts.size) != null ? _b : this.settings.thumbSize
    };
    if (opts.preset === "assets") {
      renderAssetsGallery(el, csv, renderCtx);
    } else {
      renderGenericTable(
        el,
        csv,
        renderCtx,
        (_c = opts.images) != null ? _c : this.settings.forcedImageColumns
      );
    }
  }
  /**
   * Load CSV text either from a referenced vault file or from inline content.
   * When a file is referenced, image paths in that CSV are resolved relative
   * to the CSV file's own folder (so a tables/*.csv pointing at ../assets/x.png
   * works). That is why renderCtx.sourcePath becomes opts.path above.
   */
  async loadCsvText(opts, notePath) {
    if (opts.path) {
      const resolved = this.resolveCsvPath(opts.path, notePath);
      if (!resolved) {
        throw new Error(`CSV \uD30C\uC77C\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC74C: ${opts.path}`);
      }
      return await this.app.vault.read(resolved);
    }
    if (opts.inlineCsv) {
      return opts.inlineCsv;
    }
    return null;
  }
  resolveCsvPath(path, notePath) {
    const noteDir = notePath.includes("/") ? notePath.slice(0, notePath.lastIndexOf("/")) : "";
    const candidates = [];
    if (noteDir)
      candidates.push((0, import_obsidian2.normalizePath)(`${noteDir}/${path}`));
    candidates.push((0, import_obsidian2.normalizePath)(path));
    for (const c of candidates) {
      const f = this.app.vault.getAbstractFileByPath(c);
      if (f instanceof import_obsidian2.TFile)
        return f;
    }
    const linked = this.app.metadataCache.getFirstLinkpathDest(
      path,
      notePath
    );
    return linked instanceof import_obsidian2.TFile ? linked : null;
  }
  renderError(el, msg) {
    const div = el.createDiv({ cls: "csv-img-error" });
    div.setText(`csv-img: ${msg}`);
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var CsvImgSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("\uC378\uB124\uC77C \uD06C\uAE30 (px)").setDesc("\uC774\uBBF8\uC9C0 \uC140/\uCE74\uB4DC \uC378\uB124\uC77C\uC758 \uCD5C\uB300 \uD3ED\xB7\uB192\uC774. \uBE14\uB85D\uC5D0\uC11C `size:` \uB85C \uB36E\uC5B4\uC4F8 \uC218 \uC788\uC74C.").addText(
      (t) => t.setValue(String(this.plugin.settings.thumbSize)).onChange(async (v) => {
        const n = parseInt(v, 10);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.thumbSize = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\uAC15\uC81C \uC774\uBBF8\uC9C0 \uCEEC\uB7FC (\uBC94\uC6A9 \uBAA8\uB4DC)").setDesc(
      "\uCF64\uB9C8\uB85C \uAD6C\uBD84. \uC790\uB3D9 \uAC10\uC9C0 \uB300\uC2E0 \uC774 \uCEEC\uB7FC\uB4E4\uC744 \uD56D\uC0C1 \uC774\uBBF8\uC9C0\uB85C \uB80C\uB354. \uBE14\uB85D\uC758 `images:` \uAC00 \uC6B0\uC120."
    ).addText(
      (t) => t.setValue(this.plugin.settings.forcedImageColumns.join(", ")).setPlaceholder("\uC608: file, thumbnail").onChange(async (v) => {
        this.plugin.settings.forcedImageColumns = v.split(",").map((s) => s.trim()).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "assets \uD504\uB9AC\uC14B \uCEEC\uB7FC \uB9E4\uD551" });
    containerEl.createEl("p", {
      text: "preset: assets \uAC24\uB7EC\uB9AC\uC5D0\uC11C \uAC01 \uC815\uBCF4\uB97C \uC5B4\uB290 \uCEEC\uB7FC\uC5D0\uC11C \uC77D\uC744\uC9C0 (ai-love-island assets.csv \uAE30\uBCF8\uAC12).",
      cls: "setting-item-description"
    });
    const colSetting = (name, desc, get, set) => new import_obsidian2.Setting(containerEl).setName(name).setDesc(desc).addText(
      (t) => t.setValue(get()).onChange(async (v) => {
        set(v.trim());
        await this.plugin.saveSettings();
      })
    );
    colSetting(
      "\uC774\uBBF8\uC9C0 \uACBD\uB85C \uCEEC\uB7FC",
      "\uC138\uBBF8\uCF5C\uB860(;) \uB2E4\uC911 \uACBD\uB85C \uC9C0\uC6D0",
      () => this.plugin.settings.assetsFileColumn,
      (v) => this.plugin.settings.assetsFileColumn = v
    );
    colSetting(
      "\uCEA1\uC158 \uCEEC\uB7FC",
      "",
      () => this.plugin.settings.assetsCaptionColumn,
      (v) => this.plugin.settings.assetsCaptionColumn = v
    );
    colSetting(
      "\uCD9C\uCC98 \uCEEC\uB7FC",
      "",
      () => this.plugin.settings.assetsSourceColumn,
      (v) => this.plugin.settings.assetsSourceColumn = v
    );
    colSetting(
      "\uB77C\uC774\uC120\uC2A4 \uCEEC\uB7FC",
      "",
      () => this.plugin.settings.assetsLicenseColumn,
      (v) => this.plugin.settings.assetsLicenseColumn = v
    );
    colSetting(
      "\uC5F0\uACB0 \uD45C \uCEEC\uB7FC",
      "linked_table \u2014 \uCC44\uC6CC\uC9C0\uBA74 \uC0BD\uD654, \uBE44\uBA74 \uAC24\uB7EC\uB9AC",
      () => this.plugin.settings.assetsLinkTableColumn,
      (v) => this.plugin.settings.assetsLinkTableColumn = v
    );
    colSetting(
      "\uC5F0\uACB0 \uD589 ID \uCEEC\uB7FC",
      "linked_id",
      () => this.plugin.settings.assetsLinkIdColumn,
      (v) => this.plugin.settings.assetsLinkIdColumn = v
    );
  }
};
